name: CMake Build Release and Debug
run-name: ${{ github.actor }} is compiling new things! 🚀
on: [push, pull_request]

env:
  BUILD_DIR: build
  CMAKE_VERSION: 3.20.0

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache Submodules
        uses: actions/cache@v4
        with:
          path: |
            ${{github.workspace}}/telem-in-a-box/include
          key: ${{ runner.os }}-submodules-${{ hashFiles('**/.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-
      - name: Checkout submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/telem-in-a-box
        run: git submodule update --init --recursive

      - name: Build Debug
        run: |
          cmake ../.. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
      - name: Upload Debug Build
        uses: actions/upload-artifact@v3
        with:
          name: debug-build

      - name: Build Release
        run: |
          cmake ../.. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Upload Release Build
        uses: actions/upload-artifact@v3
        with:
          name: release-build